name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: set commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: limbuhimal/python-app:${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: Argo CD Login via Port-Forward (Recommended)
        run: |
          kubectl port-forward svc/argocd-server -n argocd 8080:80 > /dev/null 2>&1 &
    
          PORT_FORWARD_PID=$!
    
          sleep 5
    
          argocd login **localhost:8080** \
          --insecure \
          --username admin \
          --password ${{ secrets.ARGOCD_PW }}
      -
        name: Sync Application
        shell: bash
        run: |
          argocd app sync python-app
      